version: '3'
services:
  decidim:
    image: decidim/decidim:latest-dev
    working_dir: "/code"
    command: bash -c "rm -f /code/development_app/tmp/pids/server.pid && cd development_app && bin/rails s"
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
      - dummy_app:/code/spec/decidim_dummy_app
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    links:
      - pg
      - redis
    ports:
      - 3000:3000
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  dummy_app: {}
  bundle: {}
  pg-data: {}
  redis-data: {}
